### ISSUE TITLE
执行think migrate命令时报错

### ISSUE THREAD

**Issue by lsliangshan** [thinkkoa/thinkkoa#1]
执行think migrate命令时报错：
Unhandled rejection Error: TypeError: lib.isScalar is not a function
    at /Keith/git/com.dei2/talk_api/node_modules/thinkorm/lib/Parser/knex.js:471:23
    at next (native)
    at step (/Keith/git/com.dei2/talk_api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Keith/git/com.dei2/talk_api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise._execute (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/promise.js:79:10)
    at /Keith/git/com.dei2/talk_api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at parseSql (/Keith/git/com.dei2/talk_api/node_modules/thinkorm/lib/Parser/knex.js:473:11)
    at buildSql (/Keith/git/com.dei2/talk_api/node_modules/thinkorm/lib/Parser/knex.js:489:21)
    at execute.then (/Keith/git/com.dei2/talk_api/node_modules/thinkorm/lib/Adapter/mysql.js:119:35)
    at tryCatcher (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Keith/git/com.dei2/talk_api/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by richenlin** [comment]
v 1.0.9 已经修复
