### ISSUE TITLE
执行think migrate报错

### ISSUE THREAD

**Issue by lsliangshan** [thinkkoa/thinkkoa#5]
Nodejs Version: v6.11.2
ThinkKoa Version: v1.7.4

执行think migrate报错：
/Keith/git/com.dei2/talk/node_modules/thinkorm/lib/model.js:86
        return schema.migrate(...args);
                      ^

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at Function.migrate (/Keith/git/com.dei2/talk/node_modules/thinkorm/lib/model.js:86:23)
    at migrateCMD (/usr/local/lib/node_modules/thinkkoa_cli/lib/index.js:527:25)
    at Command.<anonymous> (/usr/local/lib/node_modules/thinkkoa_cli/lib/index.js:569:5)
    at Command.listener (/usr/local/lib/node_modules/thinkkoa_cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/thinkkoa_cli/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/thinkkoa_cli/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/thinkkoa_cli/lib/index.js:572:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

thinkorm/lib/schema.js里没有找到migrate方法

**Comment by lsliangshan** [comment]
thinkorm  "version": "2.0.5"

**Comment by richenlin** [comment]
bug is fixed. please update thinkorm@2.0.6 & thinkorm_adapter_mysql@1.0.4
